# Project information
site_name: "Tom Waller's Polish Site"
# site_description: "MkDocs Material Boilerplate (Starter Kit) - Deploy documentation to hosting platforms (Netlify, GitHub Pages, GitLab Pages, and AWS Amplify Console) with Docker, pipenv, and GitHub Actions."
site_author: "peaceiris"
# site_url: "https://mkdocs.peaceiris.com/"

# Copyright
copyright: "&copy; 2022 Tom Waller"

# Repository
repo_name: "GitHub"
# repo_url: "https://github.com/peaceiris/mkdocs-material-boilerplate"
# edit_uri: "https://github.com/peaceiris/mkdocs-material-boilerplate/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "red"
    accent: "red"
  features:
    - tabs
  #font:
  # text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  # logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
  - tools/sentence_generator.js
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  # social:
  #   - icon: "fontawesome/brands/github-alt"
  #     link: "https://github.com/peaceiris"
  #   - icon: "fontawesome/brands/twitter"
  #     link: "https://twitter.com/piris314en"

# Page tree
nav:
    - Home: 'index.md'
    - 'Basics':
        - 'Phrases': 'basics/phrases.md'
        - 'Swadesh List': 'basics/swadesh_list.md'
    - 'Cases':
        - 'Summary': 'cases/summary.md'
        - 'Case Question Examples': 'cases/question_examples.md'
        - 'Verbs By Cases': 'cases/verb_cases.md'
    - 'Adjectives':
        - 'Conjugation': 'adjectives/adjectives_conjugation.md'
    - 'Verbs':
        - 'Summary': 'verbs/verb_summary.md'
    - 'Nouns':
        - 'Declination - Singular': 'nouns/NounDeclination-Singular.md'
        - 'Declination - Plural': 'nouns/NounDeclination-Pural.md'
        - 'Personal Pronouns': 'nouns/NounPersonalPronouns.md'
        - 'Possessive Pronouns': 'nouns/NounPossessivePronouns.md'
        - 'Relative Pronouns': 'nouns/NounRelativePronouns.md'
        - 'Demonstrative Pronouns': 'nouns/NounDemonstrativePronouns.md'
        - 'Reflexive Pronouns': 'nouns/ReflexivePronouns.md'
    - Prepositions:
        - 'Prepositions': 'prepositions/prepositions.md'
    - Numbers:
        - 'Time': 'numbers/time.md'
        - 'Dates': 'numbers/dates.md'
    - Tools:
        - 'Sentence Generator': 'tools/sentence_generator.md'
        # - 'Sentence!': 'tools/test.txt'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
